common:
  clusterDomain: ""
backend:
  name: cbomkit
  image: ghcr.io/cbomkit/cbomkit
  tag: latest
frontend:
  name: cbomkit-frontend
  image: ghcr.io/cbomkit/cbomkit-frontend
  tag: latest
regulator:
  enabled: false
  name: cbomkit-regulator
  image: ""
  tag: ""
  opa:
    name: cbomkit-opa
    image: openpolicyagent/opa
    tag: latest
postgresql:
  fullnameOverride: cbomkit-postgres
  postgresql:
  image:
    repository: bitnamilegacy/postgresql
    tag: 16.6.0
  auth:
    username: ""
    password: ""
    database: postgres
